##################################################################################################
# front-end service
##################################################################################################
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: back-end
  labels:
    app: back-end

spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - name: back-end
          image: todkap/back-end-in-memory:1.0.1
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: back-end

spec:
  ports:
    - protocol: TCP
      name: web
      port: 9080
  selector:
    app: back-end
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: back-end
spec:
  rules:
  - http:
      paths:
      - path: /storage
        pathType: Prefix
        backend:
          service:
            name: back-end
            port:
              number: 9080

---